### ISSUE TITLE
Can add user ``Hackathon`` a maintainer role for django-beanstalkd in PyPI

### ISSUE THREAD

**Issue by Brightcells** [jonasvp/django-beanstalkd#12]
This project has already UNMAINTAINED and *[django-beanstalkd](https://pypi.python.org/pypi/django-beanstalkd)* in PyPI has not release for a long time.

I wish to take over this project at *https://github.com/beanstalkdclub/django-beanstalkd*, and also wish release new versions in PyPI.

Can you add user *[Hackathon](https://pypi.org/user/Hackathon/)* a maintainer role for *[django-beanstalkd](https://pypi.python.org/pypi/django-beanstalkd)* in PyPI.

**Comment by jonasvp** [comment]
Gladly! I added `Hackathon` as a maintainer and will add a note to this project that your fork is the new canonical version. Thanks!
